
import AdminNavbar from "../../components/AdminNavbar";
import AdminSidebar from "../../components/AdminSidebar";
import { useState } from "react";
import jsPDF from "jspdf";
import "../../styles/AdminReports.css";

interface Report {
  id: number;
  title: string;
  description: string;
  date: string;
  status: string;
  count: number;
}

const AdminReports = () => {
  const [search, setSearch] = useState("");
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [generatedReport, setGeneratedReport] = useState<Report | null>(null);

  const reports: Report[] = [
    {
      id: 1,
      title: "User Registration Report",
      description: "Monthly statistics on new user registrations",
      date: "2026-08-07",
      status: "Completed",
      count: 450,
    },
    {
      id: 2,
      title: "Request Processing Analysis",
      description:
        "Analysis of request submission and completion times",
      date: "2026-08-07",
      status: "Completed",
      count: 1250,
    },
    {
      id: 3,
      title: "Office Performance Report",
      description: "Performance metrics for university offices",
      date: "2026-08-07",
      status: "Completed",
      count: 5,
    },
    {
      id: 4,
      title: "Complaint Analysis",
      description: "Complaints filed and resolution status",
      date: "2026-08-07",
      status: "In Progress",
      count: 89,
    },
  ];

  // SEARCH
  const filteredReports = reports.filter(
    (report) =>
      report.title.toLowerCase().includes(search.toLowerCase()) ||
      report.description.toLowerCase().includes(search.toLowerCase())
  );

  // GENERATE REPORT
  const generateReport = () => {
    if (filteredReports.length === 0) {
      alert("No report found");
      return;
    }

    const report: Report = {
      id: Date.now(),
      title: search
        ? `${search} Generated Report`
        : "All System Reports",
      description: search
        ? `Generated report for ${search}`
        : "Complete system report",
      date: new Date().toISOString().substring(0, 10),
      status: "Completed",
      count: filteredReports.length,
    };

    setGeneratedReport(report);
  };

  // DOWNLOAD PDF
  const downloadPDF = (report: Report) => {
    const pdf = new jsPDF();

    pdf.setFontSize(20);
    pdf.text("Campus Management System", 20, 25);

    pdf.setFontSize(16);
    pdf.text(report.title, 20, 45);

    pdf.setFontSize(12);

    pdf.text(
      `Description: ${report.description}`,
      20,
      65
    );

    pdf.text(`Date: ${report.date}`, 20, 85);

    pdf.text(`Status: ${report.status}`, 20, 105);

    pdf.text(`Total Records: ${report.count}`, 20, 125);

    pdf.setFontSize(10);
    pdf.text(
      "Generated by Campus Management System",
      20,
      145
    );

    pdf.save(
      `${report.title.replace(/[^a-z0-9]/gi, "_")}.pdf`
    );
  };

  const getStatusClass = (status: string) => {
    if (status === "Completed") {
      return "status-badge status-completed";
    }

    return "status-badge status-progress";
  };

  return (
    <div className="admin-layout">
      <AdminSidebar />

      <div className="admin-main">
        <AdminNavbar />

        <main className="reports-page">
          {/* PAGE HEADER */}
          <div className="reports-header">
            <div>
              <h1>Reports</h1>
              <p>
                View, search and generate system reports
              </p>
            </div>
          </div>

          {/* MAIN REPORT CONTAINER */}
          <section className="reports-card">

            {/* SEARCH AREA */}
            <div className="reports-toolbar">
              <div className="search-wrapper">
                <span className="search-icon">🔍</span>

                <input
                  type="text"
                  placeholder="Search reports..."
                  value={search}
                  onChange={(e) =>
                    setSearch(e.target.value)
                  }
                />

                {search && (
                  <button
                    className="clear-search"
                    onClick={() => setSearch("")}
                  >
                    ×
                  </button>
                )}
              </div>

              <button
                className="generate-btn"
                onClick={generateReport}
              >
                <span>＋</span>
                Generate Report
              </button>
            </div>

            {/* SEARCH RESULT INFO */}
            <div className="results-info">
              {search ? (
                <>
                  Showing{" "}
                  <strong>{filteredReports.length}</strong>{" "}
                  result
                  {filteredReports.length !== 1 ? "s" : ""} for{" "}
                  <strong>"{search}"</strong>
                </>
              ) : (
                <>
                  <strong>{filteredReports.length}</strong>{" "}
                  available reports
                </>
              )}
            </div>

            {/* REPORT LIST */}
            {filteredReports.length > 0 ? (
              <div className="reports-list">
                {filteredReports.map((report) => (
                  <div
                    className="report-item"
                    key={report.id}
                  >
                    {/* REPORT INFO */}
                    <div className="report-info">
                      <div className="report-title-row">
                        <h3>{report.title}</h3>

                        <span
                          className={getStatusClass(
                            report.status
                          )}
                        >
                          {report.status}
                        </span>
                      </div>

                      <p>{report.description}</p>

                      <div className="report-meta">
                        <span>
                          📅 {report.date}
                        </span>

                        <span>
                          📊 {report.count.toLocaleString()}{" "}
                          records
                        </span>
                      </div>
                    </div>

                    {/* ACTIONS */}
                    <div className="report-actions">
                      <button
                        className="view-btn"
                        onClick={() =>
                          setSelectedReport(report)
                        }
                      >
                        👁 View
                      </button>

                      <button
                        className="download-btn"
                        onClick={() =>
                          downloadPDF(report)
                        }
                      >
                        ↓ Download
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="empty-state">
                <div className="empty-icon">🔎</div>

                <h3>No reports found</h3>

                <p>
                  Try searching with a different keyword.
                </p>

                <button
                  onClick={() => setSearch("")}
                  className="reset-btn"
                >
                  Clear Search
                </button>
              </div>
            )}
          </section>
        </main>
      </div>

      {/* GENERATED REPORT MODAL */}
      {generatedReport && (
        <div
          className="modal-overlay"
          onClick={() =>
            setGeneratedReport(null)
          }
        >
          <div
            className="modal-box"
            onClick={(e) =>
              e.stopPropagation()
            }
          >
            <div className="modal-header">
              <div>
                <span className="modal-label">
                  GENERATED REPORT
                </span>

                <h2>{generatedReport.title}</h2>
              </div>

              <button
                className="modal-close"
                onClick={() =>
                  setGeneratedReport(null)
                }
              >
                ×
              </button>
            </div>

            <div className="modal-content">
              <div className="modal-description">
                {generatedReport.description}
              </div>

              <div className="modal-details">
                <div>
                  <span>Date</span>
                  <strong>
                    {generatedReport.date}
                  </strong>
                </div>

                <div>
                  <span>Status</span>
                  <strong>
                    {generatedReport.status}
                  </strong>
                </div>

                <div>
                  <span>Total Records</span>
                  <strong>
                    {generatedReport.count.toLocaleString()}
                  </strong>
                </div>
              </div>
            </div>

            <div className="modal-actions">
              <button
                className="download-btn"
                onClick={() =>
                  downloadPDF(generatedReport)
                }
              >
                ↓ Download PDF
              </button>

              <button
                className="cancel-btn"
                onClick={() =>
                  setGeneratedReport(null)
                }
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* EXISTING REPORT MODAL */}
      {selectedReport && (
        <div
          className="modal-overlay"
          onClick={() =>
            setSelectedReport(null)
          }
        >
          <div
            className="modal-box"
            onClick={(e) =>
              e.stopPropagation()
            }
          >
            <div className="modal-header">
              <div>
                <span className="modal-label">
                  REPORT DETAILS
                </span>

                <h2>{selectedReport.title}</h2>
              </div>

              <button
                className="modal-close"
                onClick={() =>
                  setSelectedReport(null)
                }
              >
                ×
              </button>
            </div>

            <div className="modal-content">
              <div className="modal-description">
                {selectedReport.description}
              </div>

              <div className="modal-details">
                <div>
                  <span>Date</span>
                  <strong>
                    {selectedReport.date}
                  </strong>
                </div>

                <div>
                  <span>Status</span>

                  <strong>
                    {selectedReport.status}
                  </strong>
                </div>

                <div>
                  <span>Total Records</span>

                  <strong>
                    {selectedReport.count.toLocaleString()}
                  </strong>
                </div>
              </div>
            </div>

            <div className="modal-actions">
              <button
                className="download-btn"
                onClick={() =>
                  downloadPDF(selectedReport)
                }
              >
                ↓ Download PDF
              </button>

              <button
                className="cancel-btn"
                onClick={() =>
                  setSelectedReport(null)
                }
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminReports;
